"""Initial migration

Revision ID: 016c4946afcd
Revises: 
Create Date: 2023-03-25 23:36:32.713807

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '016c4946afcd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=64), nullable=False),
                    sa.Column('color', sa.String(length=16), nullable=True),
                    sa.Column('cost', sa.Integer(), nullable=True),
                    sa.Column('rental_price', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('players',
                    sa.Column('id', sa.String(length=32), nullable=False),
                    sa.Column('balance', sa.Integer(), nullable=False),
                    sa.Column('position', sa.Integer(), nullable=False),
                    sa.Column('in_prison', sa.Boolean(), nullable=False),
                    sa.Column('amount_of_railroads', sa.Integer(), nullable=False),
                    sa.Column('is_bankrupt', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('games',
                    sa.Column('id', sa.String(length=32), nullable=False),
                    sa.Column('player_id', sa.String(length=32), nullable=False),
                    sa.Column('card_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('player_id', 'card_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    op.drop_table('players')
    op.drop_table('cards')
    # ### end Alembic commands ###
