"""empty message

Revision ID: 79813aafb5a4
Revises: 
Create Date: 2022-11-30 08:25:35.656591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79813aafb5a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('color', sa.String(length=256), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('rental_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('in_prison', sa.Boolean(), nullable=False),
    sa.Column('amount_of_railroads', sa.Integer(), nullable=False),
    sa.Column('is_bankrupt', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('player_id', sa.String(length=256), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'card_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    op.drop_table('players')
    op.drop_table('cards')
    # ### end Alembic commands ###
